[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["python"]
module-name = "secsgml.rust_sgml"
python-source = "secsgml"
sdist-include = ["Cargo.toml", "src/*"]